configfile: "config/config.yaml"
include: "rules/common.smk"

##### Target rules #####

rule all:
    input:
        "figures/tree_eqan.png"

##### Modules #####

include: "rules/ref.smk"
include: "rules/validation.smk"
include: "rules/persample.smk"
include: "rules/mergesamples.smk"