configfile: "config/config.yaml"

include: "rules/ref.smk"
include: "rules/validation.smk"
include: "rules/persample.smk"

rule all:
    input:
        expand("hcVCF/{sample}.vcf.gz", sample=config["samples"])
