channels:
  - conda-forge
  - bioconda
dependencies:
  - ipykernel
  - snakemake
  - google-cloud-sdk >=403.0.0
  - crcmod
  - pandas
  - gatk4
  - graphviz
  - bcftools
  - wget
  - iqtree
  - r-base
  - r-ggplot2
  - r-ape
  - r-pheatmap
  - r-RColorBrewer
  - bioconductor-treeio
  - bioconductor-ggtree