units: "config/units.tsv"

samples: ["X1a", "X1b", "X3a", "X3b", "X11", "X10_1", "X10_2"]

references:
  dbsnp_ref: Homo_sapiens_assembly38.dbsnp138.vcf
  dbsnp_ref_idx: Homo_sapiens_assembly38.dbsnp138.vcf.idx
  dict_ref: Homo_sapiens_assembly38.dict
  fasta_ref: Homo_sapiens_assembly38.fasta
  fasta_ref_idx: Homo_sapiens_assembly38.fasta.fai