units: "config/units.tsv"
samples: "config/samples.tsv"

# TODO: List conditions (columns in "config/samples.tsv") to annotate tree figures by
conditions: ["Cohort_Specific", "Platinum_Sensitivity", "Batch"]

references:
  dbsnp_ref: Homo_sapiens_assembly38.dbsnp138.vcf
  dbsnp_ref_idx: Homo_sapiens_assembly38.dbsnp138.vcf.idx
  dict_ref: Homo_sapiens_assembly38.dict
  fasta_ref: Homo_sapiens_assembly38.fasta
  fasta_ref_idx: Homo_sapiens_assembly38.fasta.fai